/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TallerCalidad;

public class Operaciones {
    public boolean someLibraryMethod() {
        return true;
    }

    public String resumenCurso(int notaBimestreUno, int notaBimestreDos) {
        if (notaBimestreUno + notaBimestreDos >= 14)
            return "Aprueba";
        else if (notaBimestreUno + notaBimestreDos >= 10 || notaBimestreUno + notaBimestreDos >= 13)
            return "Supletorio";
        else if (notaBimestreUno + notaBimestreDos < 10)
            return "Reprueba";
        else
            return "error";
    }
}
